smtp_on: true
smtp_host: in-v3.mailjet.com
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: tls
smtp_autotls: true
smtp_timeout: 30
smtp_username: fbd16c108329fff2b263632cfcad08fc
smtp_password: 27e96021e5fd721410d910a78e237c51
smtp_from: ne-pas-repondre@cesanneesincroyables.fr
smtp_fromname: 'Ces Années Incroyables'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
smtp_keepalive: false
_core:
  default_config_hash: 2v5R3I9tNatGzKQjuZWh1y_955xK09313Vn-IIuedyI
langcode: fr
