access_filter.filter.*:
  type: config_entity
  label: 'Access filter'
  mapping:
    id:
      type: string
      label: 'Filter identifier'
    name:
      type: label
      label: 'Name'
    status:
      type: integer
      label: 'Status'
    conditions:
      type: string
      label: 'Conditions'
    rules:
      type: string
      label: 'Rules'
    response:
      type: string
      label: 'Response'
    uuid:
      type: string
      label: 'UUID'
    weight:
      type: integer
      label: 'Weight'
