verbose: 1
types:
  block_content: {  }
  comment: {  }
  file: {  }
  node:
    '*': '*'
  oauth2_server_authorization_code: {  }
  oauth2_server_token: {  }
  oauth2_server_jti: {  }
  paragraphs_library_item: {  }
  path_alias: {  }
  shortcut: {  }
  taxonomy_term: {  }
  user: {  }
  webform_submission: {  }
  menu_link_content: {  }
  paragraph: {  }
types_translation_lock: {  }
types_js_lock: {  }
form_op_lock:
  block_content:
    mode: 0
    values: {  }
  comment:
    mode: 0
    values: {  }
  file:
    mode: 0
    values: {  }
  node:
    mode: 0
    values: {  }
  oauth2_server_authorization_code:
    mode: 0
    values: {  }
  oauth2_server_token:
    mode: 0
    values: {  }
  oauth2_server_jti:
    mode: 0
    values: {  }
  paragraphs_library_item:
    mode: 0
    values: {  }
  path_alias:
    mode: 0
    values: {  }
  shortcut:
    mode: 0
    values: {  }
  taxonomy_term:
    mode: 0
    values: {  }
  user:
    mode: 0
    values: {  }
  webform_submission:
    mode: 0
    values: {  }
  menu_link_content:
    mode: 0
    values: {  }
  paragraph:
    mode: 0
    values: {  }
_core:
  default_config_hash: 6Ka3T1c-CIjEUO1Q64NXKksLthkMhj53a6zy4RJBtkc
langcode: fr
