content_access_roles_gids:
  anonymous: 1
  authenticated: 2
  administrator: 3
  editeur: 5
  animateur: 10
  parent: 18
  professionnel: 19
  abonne: 20
_core:
  default_config_hash: 7LkiviGITIpniIOOIzpuxR7r4XzqqYN_cwu0fb0kx1M
langcode: fr
content_access_node_type:
  page: 'a:1:{s:8:"per_node";i:1;}'
